version: '3'

services:
  app:
    build:
      context: .
    container_name: rating_service_app
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://rating_service_mongodb:27017/test
    ports:
      - "4001:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: rating_service_mongodb
    ports:
      - "27018:27017"
