version: '3'

services:
  app:
    build:
      context: .
    container_name: rating_service_app
    environment:
      - MONGO_HOST=rating_service_mongodb
      - MONGO_DB=test1
      - MONGO_INITDB_ROOT_USERNAME=pera1
      - MONGO_INITDB_ROOT_PASSWORD=pera1
    ports:
      - "4001:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: rating_service_mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_DB=test1
      - MONGO_INITDB_ROOT_USERNAME=pera1
      - MONGO_INITDB_ROOT_PASSWORD=pera1
